apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-tj4m
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-tj4m
    app.kubernetes.io/part-of: tkwch-fix-0075-0053-app
  name: devfile-sample-tj4m
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-tj4m
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-tj4m
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0053-tenant/tkwch-fix-0075-0053-app/devfile-sample-tj4m@sha256:75efbbfdc95a30c02eee9f1200bc1debe85b2961859067860460cf6ce0b7c824
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
